-- TechPulse database schema
-- Run this entire file in Supabase Dashboard > SQL Editor.

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text not null,
  url text not null unique,
  image_url text,
  source text,
  category text not null,
  created_at timestamptz not null default now()
);

-- Recreate named constraints so this file safely upgrades an older installation.
alter table public.articles drop constraint if exists articles_title_length_check;
alter table public.articles add constraint articles_title_length_check
  check (char_length(btrim(title)) between 1 and 300);

alter table public.articles drop constraint if exists articles_content_length_check;
alter table public.articles add constraint articles_content_length_check
  check (char_length(btrim(content)) between 1 and 100000);

alter table public.articles drop constraint if exists articles_url_length_check;
alter table public.articles add constraint articles_url_length_check
  check (char_length(btrim(url)) between 10 and 2048);

alter table public.articles drop constraint if exists articles_source_url_check;
alter table public.articles add constraint articles_source_url_check
  check (btrim(url) ~* '^https?://');

alter table public.articles drop constraint if exists articles_image_url_check;
alter table public.articles add constraint articles_image_url_check
  check (image_url is null or btrim(image_url) = '' or btrim(image_url) ~* '^https?://');

alter table public.articles drop constraint if exists articles_category_check;
alter table public.articles add constraint articles_category_check
  check (category in ('هوش مصنوعی', 'تکنولوژی', 'علم', 'کسب‌وکار'));

create index if not exists articles_created_at_idx
  on public.articles (created_at desc);
create index if not exists articles_category_created_at_idx
  on public.articles (category, created_at desc);

alter table public.articles enable row level security;
drop policy if exists "public can read articles" on public.articles;
create policy "public can read articles"
  on public.articles
  for select
  to anon, authenticated
  using (true);

-- Browser clients may read published articles if an anon client is ever introduced,
-- but cannot insert, update, or delete. This project currently reads through the API only.
revoke all on table public.articles from anon, authenticated;
grant select on table public.articles to anon, authenticated;
grant usage, select on sequence public.articles_id_seq to service_role;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages drop constraint if exists contact_messages_name_length_check;
alter table public.contact_messages add constraint contact_messages_name_length_check
  check (char_length(btrim(name)) between 2 and 120);

alter table public.contact_messages drop constraint if exists contact_messages_message_length_check;
alter table public.contact_messages add constraint contact_messages_message_length_check
  check (char_length(btrim(message)) between 5 and 5000);

alter table public.contact_messages enable row level security;
drop policy if exists "no public access to contact messages" on public.contact_messages;
create policy "no public access to contact messages"
  on public.contact_messages
  for all
  to anon, authenticated
  using (false)
  with check (false);

revoke all on table public.contact_messages from anon, authenticated;
grant usage, select on sequence public.contact_messages_id_seq to service_role;
