create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text not null,
  url text not null unique,
  image_url text,
  source text,
  category text not null check (category in ('هوش مصنوعی','تکنولوژی','علم','کسب‌وکار')),
  created_at timestamptz not null default now()
);
create index if not exists articles_created_at_idx on public.articles(created_at desc);
create index if not exists articles_category_created_at_idx on public.articles(category, created_at desc);
alter table public.articles enable row level security;
drop policy if exists "public can read articles" on public.articles;
create policy "public can read articles" on public.articles for select to anon, authenticated using (true);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);
alter table public.contact_messages enable row level security;
drop policy if exists "no public access to contact messages" on public.contact_messages;
create policy "no public access to contact messages" on public.contact_messages for all to anon, authenticated using (false) with check (false);
