create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  excerpt text,
  content text not null check (char_length(btrim(content)) between 1 and 100000),
  url text not null unique check (char_length(btrim(url)) between 10 and 2048),
  image_url text,
  source text,
  category text not null check (category in ('هوش مصنوعی','تکنولوژی','علم','کسب‌وکار')),
  created_at timestamptz not null default now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'articles_source_url_check') THEN
    ALTER TABLE public.articles ADD CONSTRAINT articles_source_url_check CHECK (left(btrim(url), 7) in ('http://','https://'));
  END IF;
END $$;

create index if not exists articles_created_at_idx on public.articles(created_at desc);
create index if not exists articles_category_created_at_idx on public.articles(category, created_at desc);

alter table public.articles enable row level security;
drop policy if exists "public can read articles" on public.articles;
create policy "public can read articles" on public.articles for select to anon, authenticated using (true);
revoke all on public.articles from anon, authenticated;
grant select on public.articles to anon, authenticated;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  message text not null check (char_length(btrim(message)) between 5 and 5000),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;
drop policy if exists "no public access to contact messages" on public.contact_messages;
create policy "no public access to contact messages" on public.contact_messages for all to anon, authenticated using (false) with check (false);
revoke all on public.contact_messages from anon, authenticated;
