create schema if not exists extensions;
alter extension pg_trgm set schema extensions;
create index if not exists audit_logs_actor_idx on public.audit_logs (actor_id, created_at desc);
create index if not exists comments_user_idx on public.comments (user_id, created_at desc);
create index if not exists favorites_listing_idx on public.favorites (listing_id, created_at desc);
create index if not exists ratings_user_idx on public.ratings (user_id, created_at desc);
create index if not exists reports_user_idx on public.reports (user_id, created_at desc);
-- RLS policies are written with (select auth.uid()) so auth context is initialized once per query.
-- Existing policies from 0001 are replaced here with equivalent optimized predicates.
DROP POLICY IF EXISTS profiles_select_self_or_admin ON public.profiles;
CREATE POLICY profiles_select_self_or_admin ON public.profiles FOR SELECT TO authenticated USING ((id = (select auth.uid())) OR private.is_admin());
DROP POLICY IF EXISTS profiles_update_self ON public.profiles;
CREATE POLICY profiles_update_self ON public.profiles FOR UPDATE TO authenticated USING ((id = (select auth.uid())) AND NOT private.is_admin()) WITH CHECK ((id = (select auth.uid())) AND NOT private.is_admin());
DROP POLICY IF EXISTS profile_private_self ON public.profile_private;
CREATE POLICY profile_private_self ON public.profile_private FOR SELECT TO authenticated USING (id = (select auth.uid()));
DROP POLICY IF EXISTS profile_private_update ON public.profile_private;
CREATE POLICY profile_private_update ON public.profile_private FOR INSERT TO authenticated WITH CHECK (id = (select auth.uid()));
DROP POLICY IF EXISTS profile_private_upd ON public.profile_private;
CREATE POLICY profile_private_upd ON public.profile_private FOR UPDATE TO authenticated USING (id = (select auth.uid())) WITH CHECK (id = (select auth.uid()));
DROP POLICY IF EXISTS listings_public_or_owner_select ON public.listings;
CREATE POLICY listings_public_or_owner_select ON public.listings FOR SELECT TO anon, authenticated USING ((active = true AND hidden = false) OR seller_id = (select auth.uid()) OR private.is_admin());
DROP POLICY IF EXISTS listings_insert_seller ON public.listings;
CREATE POLICY listings_insert_seller ON public.listings FOR INSERT TO authenticated WITH CHECK (seller_id = (select auth.uid()) AND EXISTS (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'seller' and p.suspended = false));
DROP POLICY IF EXISTS listings_update_owner_admin ON public.listings;
CREATE POLICY listings_update_owner_admin ON public.listings FOR UPDATE TO authenticated USING (seller_id = (select auth.uid()) OR private.is_admin()) WITH CHECK (seller_id = (select auth.uid()) OR private.is_admin());
DROP POLICY IF EXISTS listings_delete_owner_admin ON public.listings;
CREATE POLICY listings_delete_owner_admin ON public.listings FOR DELETE TO authenticated USING (seller_id = (select auth.uid()) OR private.is_admin());
DROP POLICY IF EXISTS ratings_insert ON public.ratings;
CREATE POLICY ratings_insert ON public.ratings FOR INSERT TO authenticated WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS ratings_update ON public.ratings;
CREATE POLICY ratings_update ON public.ratings FOR UPDATE TO authenticated USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS ratings_delete ON public.ratings;
CREATE POLICY ratings_delete ON public.ratings FOR DELETE TO authenticated USING (user_id = (select auth.uid()) OR private.is_admin());
DROP POLICY IF EXISTS reports_insert ON public.reports;
CREATE POLICY reports_insert ON public.reports FOR INSERT TO authenticated WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS reports_delete_admin ON public.reports;
CREATE POLICY reports_delete_admin ON public.reports FOR DELETE TO authenticated USING (private.is_admin());
DROP POLICY IF EXISTS comments_insert ON public.comments;
CREATE POLICY comments_insert ON public.comments FOR INSERT TO authenticated WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS comments_delete ON public.comments;
CREATE POLICY comments_delete ON public.comments FOR DELETE TO authenticated USING (user_id = (select auth.uid()) OR private.is_admin());
DROP POLICY IF EXISTS favorites_select ON public.favorites;
CREATE POLICY favorites_select ON public.favorites FOR SELECT TO authenticated USING (user_id = (select auth.uid()));
DROP POLICY IF EXISTS favorites_insert ON public.favorites;
CREATE POLICY favorites_insert ON public.favorites FOR INSERT TO authenticated WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS favorites_delete ON public.favorites;
CREATE POLICY favorites_delete ON public.favorites FOR DELETE TO authenticated USING (user_id = (select auth.uid()));
DROP POLICY IF EXISTS audit_logs_admin ON public.audit_logs;
CREATE POLICY audit_logs_admin ON public.audit_logs FOR SELECT TO authenticated USING (private.is_admin());
